// <auto-generated />
using CatTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatTracker.Data.Migrations
{
    [DbContext(typeof(CatContext))]
    partial class CatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CatTracker.Core.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RaisedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaisedUtc");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CatTracker.Core.Excursion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CoverageRatio")
                        .HasColumnType("REAL");

                    b.Property<long>("DepartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDistanceM")
                        .HasColumnType("REAL");

                    b.Property<long?>("ReturnedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId", "DepartedUtc");

                    b.ToTable("Excursions");
                });

            modelBuilder.Entity("CatTracker.Core.Fix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("BatteryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HorizontalAccuracy")
                        .HasColumnType("REAL");

                    b.Property<long>("IngestedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInaccurate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOld")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PositionType")
                        .HasColumnType("TEXT");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Fixes");
                });

            modelBuilder.Entity("CatTracker.Core.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindMyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CatTracker.Core.Zone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<double>("ExitBufferM")
                        .HasColumnType("REAL");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnEnter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnExit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RadiusM")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("CatTracker.Core.ZoneEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FixId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("TagId", "OccurredUtc");

                    b.ToTable("ZoneEvents");
                });

            modelBuilder.Entity("CatTracker.Core.ZoneTrackerState", b =>
                {
                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId", "ZoneId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneStates");
                });

            modelBuilder.Entity("CatTracker.Data.RawSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CapturedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapturedUtc");

                    b.ToTable("RawSnapshots");
                });

            modelBuilder.Entity("CatTracker.Core.Excursion", b =>
                {
                    b.HasOne("CatTracker.Core.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatTracker.Core.Fix", b =>
                {
                    b.HasOne("CatTracker.Core.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatTracker.Core.ZoneEvent", b =>
                {
                    b.HasOne("CatTracker.Core.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatTracker.Core.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatTracker.Core.ZoneTrackerState", b =>
                {
                    b.HasOne("CatTracker.Core.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatTracker.Core.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
